services:
  mysql:
    image: mysql:8.0
    container_name: eneb453_lab4_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: eneb453_lab4
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
